apiVersion: v1
kind: Secret
metadata:
  name: sweldotrack-secrets
  namespace: sweldotrack
type: Opaque
stringData:
  DB_PASSWORD: "Water123!!"
  JWT_SECRET: "sweldotrack-dev-secret"
  NEXTAUTH_SECRET: "sweldotrack-nextauth-secret"
  POSTGRES_PASSWORD: "Water123!!"